config/routes.rb
Rails.application.routes.draw do
  
  root to: 'posts#index'

	get '/login' => 'admin/sessions#new'
	get '/logout' => 'admin/sessions#destroy'
	
  namespace :admin do
    resources :posts
    resources :settings, only: [:new, :create, :edit, :update] 
    resources :dashboard, only: [:index]
    resources :notifications, only: [:index, :destroy]
    resources :messages, only: [:index, :show, :update, :destroy]
    resources :visitors, only: [:index, :destroy]
    resources :comments, only: [:index, :update, :destroy]
    resources :tags, except: [:index]
	resources :sessions, only: [:new, :create, :destroy]
	resources :moderators, only: [:index, :edit, :update]
	end

  resources :posts, only: [:index, :show]
  resources :messages, only: [:new, :create]
  resources :comments, only: [:create]

    match 'dismiss_all_notifications', to: 'admin/notifications#delete_all', via: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :visitor
  has_many :notifications, as: :notifiable, dependent: :destroy

  def self.matching_fullname_or_message params
  	joins(:visitor).where("fullname LIKE ? OR message LIKE ?", "%#{params}%", "%#{params}%")
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :visitor

  def self.matching_fullname_or_content params
  	joins(:visitor).where("fullname LIKE ? OR content LIKE ?", "%#{params}", "%#{params}")
  end

  def mark_read
  	update(status: true) if status == false
  end
end

app/models/moderator.rb
class Moderator < ApplicationRecord
	has_secure_password

	has_many :posts

	validates :fullname, presence: true
	validates :username, presence: true, format: {with: /@/, message: 'is not valid'}
	validates :password, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  belongs_to :moderator

  validates :title, presence: true
  validates :content, presence: true

  def self.matching_title_or_content search
  	where("title LIKE? OR content LIKE ?", "%#{search}%", "#{search}%")
  end

  def self.filter_by_tags param_tag
  	includes(:tags).where(publish: true, tags: {name: param_tag}).order(id: :desc)
  end
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/setting.rb
class Setting < ActiveRecord::Base
	def self.site_name
		Setting.first.try(:site_name)
	end

	def self.post_per_page
		Setting.first.try(:post_per_page)
	end

	def self.tag_visible?
		Setting.first.try(:tag_visibility)
	end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :posts, through: :post_tags

	validates :name, presence: true

	def in_use?
		PostTag.exists?(tag_id: self.id)
	end
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
	has_many :notifications, as: :notifiable, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :messages, dependent: :destroy

	accepts_nested_attributes_for :comments
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index
  	@posts = Post.last 5
  	@comments = Comment.last 5
  	@visitors = Visitor.last 5
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@visitor = Visitor.new(visitor_comments_params)
  	@visitor.save

  	redirect_back(fallback_location: root_path)
  end


  private

  def visitor_comments_params
  	params.require(:visitor).permit(:fullname, :email, :comments_attributes => [:message, :post_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	if params[:tag]
  		@posts = Post.filter_by_tags(params[:tag]).page(params[:page]).per(Setting.post_per_page)
  	else		
  	@posts = Post.where(publish: true).order(id: :desc).page(params[:page]).per(Setting.post_per_page)
  	end
  end

  def show
  	@post = Post.find(params[:id])
  	@visitor_comment = Visitor.new(comments: [Comment.new])
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
	def create_deletable_button tag
		if tag.in_use?
	 		link_to '#' do
	 			content_tag(:button, 'Delete', class: 'disabled')
	 		end
	 	else
		 	link_to admin_tag_path(tag), method: :delete do
		 		content_tag(:button, 'Delete')
		 	end 
	  	end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def status_converter(status, truthy: 'Active', falsey: 'Pending')
		if status
			truthy
		else
			falsey
		end
	end

	def time_ago time
		"#{time_ago_in_words(time)} ago"
	end

	def double_digit_number n
		'%02d' % n
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Dashboard</h1>

<h2>Post</h2>
<%= link_to 'create new post', new_admin_post_path %><br>
<%= link_to 'list posts', admin_posts_path %>

<table class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>title</th>
			<th>replies</th>
			<th>date</th>
			<th>actions</th>
		</tr>
	</thead>
	<tbody>
		<% @posts.each do |post| %>
			<tr>
				<td><%= truncate(post.title, length: 40, separator: '') %></td>
				<td><%= post.comments.count %></td>
				<td><%= time_ago post.created_at %></td>
				<td>
					<%= link_to 'edit', edit_admin_post_path(post) %>
					<%= link_to 'view', admin_post_path(post) %>
					<%= link_to 'delete', admin_post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %>

				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<h2>Comments</h2>
<%= link_to 'list all comments', admin_comments_path %>

<% @comments.each do |comment| %>
<p><%= comment.visitor.fullname %></p>
<p><%= truncate(comment.message, length: 125, separator: '') %></p>
<p><%= time_ago comment.created_at %></p>
<hr>
<% end %>

<h2>Visitors</h2>
<table class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>#</th>
			<th>Full Name</th>
			<th>Email</th>
			<th>Created</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @visitors.each_with_index do |visitor, index| %>
		<tr>
			<td><%= index + 1 %></td>
			<td><%= visitor.fullname %></td>
			<td><%= visitor.email %></td>
			<td><%= time_ago visitor.created_at %></td>
			<td>
				<%= link_to 'delete', admin_visitor_path(visitor), method: :delete, data: {confirm: 'Are you sure?'} %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>